# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import analytics_pb2 as analytics__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in analytics_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class AnalyticsServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.GetTimelineAll = channel.unary_unary(
                '/analytics.AnalyticsService/GetTimelineAll',
                request_serializer=analytics__pb2.GetTimelineAllRequest.SerializeToString,
                response_deserializer=analytics__pb2.TimelineResponse.FromString,
                _registered_method=True)
        self.GetTimelineProject = channel.unary_unary(
                '/analytics.AnalyticsService/GetTimelineProject',
                request_serializer=analytics__pb2.GetTimelineProjectRequest.SerializeToString,
                response_deserializer=analytics__pb2.TimelineResponse.FromString,
                _registered_method=True)
        self.GetTimelineAllMine = channel.unary_unary(
                '/analytics.AnalyticsService/GetTimelineAllMine',
                request_serializer=analytics__pb2.GetTimelineAllMineRequest.SerializeToString,
                response_deserializer=analytics__pb2.TimelineResponse.FromString,
                _registered_method=True)
        self.GetTimelineProjectMine = channel.unary_unary(
                '/analytics.AnalyticsService/GetTimelineProjectMine',
                request_serializer=analytics__pb2.GetTimelineProjectMineRequest.SerializeToString,
                response_deserializer=analytics__pb2.TimelineResponse.FromString,
                _registered_method=True)
        self.GetTasksCompletedByUser = channel.unary_unary(
                '/analytics.AnalyticsService/GetTasksCompletedByUser',
                request_serializer=analytics__pb2.GetTasksCompletedByUserRequest.SerializeToString,
                response_deserializer=analytics__pb2.TasksCompletedByUserResponse.FromString,
                _registered_method=True)
        self.GetTasksStatusInSprints = channel.unary_unary(
                '/analytics.AnalyticsService/GetTasksStatusInSprints',
                request_serializer=analytics__pb2.GetTasksStatusInSprintsRequest.SerializeToString,
                response_deserializer=analytics__pb2.TasksStatusInSprintsResponse.FromString,
                _registered_method=True)
        self.GetTasksProgressByDay = channel.unary_unary(
                '/analytics.AnalyticsService/GetTasksProgressByDay',
                request_serializer=analytics__pb2.GetTasksProgressByDayRequest.SerializeToString,
                response_deserializer=analytics__pb2.TasksProgressByDayResponse.FromString,
                _registered_method=True)


class AnalyticsServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def GetTimelineAll(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTimelineProject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTimelineAllMine(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTimelineProjectMine(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTasksCompletedByUser(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTasksStatusInSprints(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetTasksProgressByDay(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_AnalyticsServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'GetTimelineAll': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTimelineAll,
                    request_deserializer=analytics__pb2.GetTimelineAllRequest.FromString,
                    response_serializer=analytics__pb2.TimelineResponse.SerializeToString,
            ),
            'GetTimelineProject': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTimelineProject,
                    request_deserializer=analytics__pb2.GetTimelineProjectRequest.FromString,
                    response_serializer=analytics__pb2.TimelineResponse.SerializeToString,
            ),
            'GetTimelineAllMine': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTimelineAllMine,
                    request_deserializer=analytics__pb2.GetTimelineAllMineRequest.FromString,
                    response_serializer=analytics__pb2.TimelineResponse.SerializeToString,
            ),
            'GetTimelineProjectMine': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTimelineProjectMine,
                    request_deserializer=analytics__pb2.GetTimelineProjectMineRequest.FromString,
                    response_serializer=analytics__pb2.TimelineResponse.SerializeToString,
            ),
            'GetTasksCompletedByUser': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTasksCompletedByUser,
                    request_deserializer=analytics__pb2.GetTasksCompletedByUserRequest.FromString,
                    response_serializer=analytics__pb2.TasksCompletedByUserResponse.SerializeToString,
            ),
            'GetTasksStatusInSprints': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTasksStatusInSprints,
                    request_deserializer=analytics__pb2.GetTasksStatusInSprintsRequest.FromString,
                    response_serializer=analytics__pb2.TasksStatusInSprintsResponse.SerializeToString,
            ),
            'GetTasksProgressByDay': grpc.unary_unary_rpc_method_handler(
                    servicer.GetTasksProgressByDay,
                    request_deserializer=analytics__pb2.GetTasksProgressByDayRequest.FromString,
                    response_serializer=analytics__pb2.TasksProgressByDayResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'analytics.AnalyticsService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('analytics.AnalyticsService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class AnalyticsService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def GetTimelineAll(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetTimelineAll',
            analytics__pb2.GetTimelineAllRequest.SerializeToString,
            analytics__pb2.TimelineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTimelineProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetTimelineProject',
            analytics__pb2.GetTimelineProjectRequest.SerializeToString,
            analytics__pb2.TimelineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTimelineAllMine(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetTimelineAllMine',
            analytics__pb2.GetTimelineAllMineRequest.SerializeToString,
            analytics__pb2.TimelineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTimelineProjectMine(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetTimelineProjectMine',
            analytics__pb2.GetTimelineProjectMineRequest.SerializeToString,
            analytics__pb2.TimelineResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTasksCompletedByUser(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetTasksCompletedByUser',
            analytics__pb2.GetTasksCompletedByUserRequest.SerializeToString,
            analytics__pb2.TasksCompletedByUserResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTasksStatusInSprints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetTasksStatusInSprints',
            analytics__pb2.GetTasksStatusInSprintsRequest.SerializeToString,
            analytics__pb2.TasksStatusInSprintsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetTasksProgressByDay(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/analytics.AnalyticsService/GetTasksProgressByDay',
            analytics__pb2.GetTasksProgressByDayRequest.SerializeToString,
            analytics__pb2.TasksProgressByDayResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
