# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from . import pm_pb2 as pm__pb2

GRPC_GENERATED_VERSION = '1.71.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in pm_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class ProjectServiceStub(object):
    """Missing associated documentation comment in .proto file."""

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.CreateProject = channel.unary_unary(
                '/project.ProjectService/CreateProject',
                request_serializer=pm__pb2.CreateProjectRequest.SerializeToString,
                response_deserializer=pm__pb2.ProjectResponse.FromString,
                _registered_method=True)
        self.GetProject = channel.unary_unary(
                '/project.ProjectService/GetProject',
                request_serializer=pm__pb2.GetProjectRequest.SerializeToString,
                response_deserializer=pm__pb2.ProjectResponse.FromString,
                _registered_method=True)
        self.UpdateProject = channel.unary_unary(
                '/project.ProjectService/UpdateProject',
                request_serializer=pm__pb2.UpdateProjectRequest.SerializeToString,
                response_deserializer=pm__pb2.ProjectResponse.FromString,
                _registered_method=True)
        self.UpdateProjectImg = channel.unary_unary(
                '/project.ProjectService/UpdateProjectImg',
                request_serializer=pm__pb2.UpdateProjectImgRequest.SerializeToString,
                response_deserializer=pm__pb2.ProjectResponse.FromString,
                _registered_method=True)
        self.UpdateProjectUsers = channel.unary_unary(
                '/project.ProjectService/UpdateProjectUsers',
                request_serializer=pm__pb2.UpdateProjectUsersRequest.SerializeToString,
                response_deserializer=pm__pb2.UpdateProjectUsersResponse.FromString,
                _registered_method=True)
        self.DeleteProject = channel.unary_unary(
                '/project.ProjectService/DeleteProject',
                request_serializer=pm__pb2.DeleteProjectRequest.SerializeToString,
                response_deserializer=pm__pb2.DeleteProjectResponse.FromString,
                _registered_method=True)
        self.GetUserProjects = channel.unary_unary(
                '/project.ProjectService/GetUserProjects',
                request_serializer=pm__pb2.GetUserProjectsRequest.SerializeToString,
                response_deserializer=pm__pb2.UserProjectsResponse.FromString,
                _registered_method=True)
        self.GetProjectUsers = channel.unary_unary(
                '/project.ProjectService/GetProjectUsers',
                request_serializer=pm__pb2.GetProjectUsersRequest.SerializeToString,
                response_deserializer=pm__pb2.ProjectUsersResponse.FromString,
                _registered_method=True)
        self.GetSprint = channel.unary_unary(
                '/project.ProjectService/GetSprint',
                request_serializer=pm__pb2.GetSprintRequest.SerializeToString,
                response_deserializer=pm__pb2.SprintResponse.FromString,
                _registered_method=True)
        self.GetProjectSprints = channel.unary_unary(
                '/project.ProjectService/GetProjectSprints',
                request_serializer=pm__pb2.GetProjectSprintsRequest.SerializeToString,
                response_deserializer=pm__pb2.ProjectSprintsResponse.FromString,
                _registered_method=True)
        self.CreateSprint = channel.unary_unary(
                '/project.ProjectService/CreateSprint',
                request_serializer=pm__pb2.CreateSprintRequest.SerializeToString,
                response_deserializer=pm__pb2.SprintResponse.FromString,
                _registered_method=True)
        self.UpdateSprint = channel.unary_unary(
                '/project.ProjectService/UpdateSprint',
                request_serializer=pm__pb2.UpdateSprintRequest.SerializeToString,
                response_deserializer=pm__pb2.SprintResponse.FromString,
                _registered_method=True)
        self.DeleteSprint = channel.unary_unary(
                '/project.ProjectService/DeleteSprint',
                request_serializer=pm__pb2.DeleteSprintRequest.SerializeToString,
                response_deserializer=pm__pb2.DeleteSprintResponse.FromString,
                _registered_method=True)
        self.GetEpic = channel.unary_unary(
                '/project.ProjectService/GetEpic',
                request_serializer=pm__pb2.GetEpicRequest.SerializeToString,
                response_deserializer=pm__pb2.EpicResponse.FromString,
                _registered_method=True)
        self.GetProjectEpics = channel.unary_unary(
                '/project.ProjectService/GetProjectEpics',
                request_serializer=pm__pb2.GetProjectEpicsRequest.SerializeToString,
                response_deserializer=pm__pb2.ProjectEpicsResponse.FromString,
                _registered_method=True)
        self.CreateEpic = channel.unary_unary(
                '/project.ProjectService/CreateEpic',
                request_serializer=pm__pb2.CreateEpicRequest.SerializeToString,
                response_deserializer=pm__pb2.EpicResponse.FromString,
                _registered_method=True)
        self.UpdateEpic = channel.unary_unary(
                '/project.ProjectService/UpdateEpic',
                request_serializer=pm__pb2.UpdateEpicRequest.SerializeToString,
                response_deserializer=pm__pb2.EpicResponse.FromString,
                _registered_method=True)
        self.DeleteEpic = channel.unary_unary(
                '/project.ProjectService/DeleteEpic',
                request_serializer=pm__pb2.DeleteEpicRequest.SerializeToString,
                response_deserializer=pm__pb2.DeleteEpicResponse.FromString,
                _registered_method=True)


class ProjectServiceServicer(object):
    """Missing associated documentation comment in .proto file."""

    def CreateProject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProjectImg(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateProjectUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteProject(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetUserProjects(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProjectUsers(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetSprint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProjectSprints(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateSprint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateSprint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteSprint(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetEpic(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def GetProjectEpics(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def CreateEpic(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def UpdateEpic(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def DeleteEpic(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_ProjectServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'CreateProject': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateProject,
                    request_deserializer=pm__pb2.CreateProjectRequest.FromString,
                    response_serializer=pm__pb2.ProjectResponse.SerializeToString,
            ),
            'GetProject': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProject,
                    request_deserializer=pm__pb2.GetProjectRequest.FromString,
                    response_serializer=pm__pb2.ProjectResponse.SerializeToString,
            ),
            'UpdateProject': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProject,
                    request_deserializer=pm__pb2.UpdateProjectRequest.FromString,
                    response_serializer=pm__pb2.ProjectResponse.SerializeToString,
            ),
            'UpdateProjectImg': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProjectImg,
                    request_deserializer=pm__pb2.UpdateProjectImgRequest.FromString,
                    response_serializer=pm__pb2.ProjectResponse.SerializeToString,
            ),
            'UpdateProjectUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateProjectUsers,
                    request_deserializer=pm__pb2.UpdateProjectUsersRequest.FromString,
                    response_serializer=pm__pb2.UpdateProjectUsersResponse.SerializeToString,
            ),
            'DeleteProject': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteProject,
                    request_deserializer=pm__pb2.DeleteProjectRequest.FromString,
                    response_serializer=pm__pb2.DeleteProjectResponse.SerializeToString,
            ),
            'GetUserProjects': grpc.unary_unary_rpc_method_handler(
                    servicer.GetUserProjects,
                    request_deserializer=pm__pb2.GetUserProjectsRequest.FromString,
                    response_serializer=pm__pb2.UserProjectsResponse.SerializeToString,
            ),
            'GetProjectUsers': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProjectUsers,
                    request_deserializer=pm__pb2.GetProjectUsersRequest.FromString,
                    response_serializer=pm__pb2.ProjectUsersResponse.SerializeToString,
            ),
            'GetSprint': grpc.unary_unary_rpc_method_handler(
                    servicer.GetSprint,
                    request_deserializer=pm__pb2.GetSprintRequest.FromString,
                    response_serializer=pm__pb2.SprintResponse.SerializeToString,
            ),
            'GetProjectSprints': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProjectSprints,
                    request_deserializer=pm__pb2.GetProjectSprintsRequest.FromString,
                    response_serializer=pm__pb2.ProjectSprintsResponse.SerializeToString,
            ),
            'CreateSprint': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateSprint,
                    request_deserializer=pm__pb2.CreateSprintRequest.FromString,
                    response_serializer=pm__pb2.SprintResponse.SerializeToString,
            ),
            'UpdateSprint': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateSprint,
                    request_deserializer=pm__pb2.UpdateSprintRequest.FromString,
                    response_serializer=pm__pb2.SprintResponse.SerializeToString,
            ),
            'DeleteSprint': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteSprint,
                    request_deserializer=pm__pb2.DeleteSprintRequest.FromString,
                    response_serializer=pm__pb2.DeleteSprintResponse.SerializeToString,
            ),
            'GetEpic': grpc.unary_unary_rpc_method_handler(
                    servicer.GetEpic,
                    request_deserializer=pm__pb2.GetEpicRequest.FromString,
                    response_serializer=pm__pb2.EpicResponse.SerializeToString,
            ),
            'GetProjectEpics': grpc.unary_unary_rpc_method_handler(
                    servicer.GetProjectEpics,
                    request_deserializer=pm__pb2.GetProjectEpicsRequest.FromString,
                    response_serializer=pm__pb2.ProjectEpicsResponse.SerializeToString,
            ),
            'CreateEpic': grpc.unary_unary_rpc_method_handler(
                    servicer.CreateEpic,
                    request_deserializer=pm__pb2.CreateEpicRequest.FromString,
                    response_serializer=pm__pb2.EpicResponse.SerializeToString,
            ),
            'UpdateEpic': grpc.unary_unary_rpc_method_handler(
                    servicer.UpdateEpic,
                    request_deserializer=pm__pb2.UpdateEpicRequest.FromString,
                    response_serializer=pm__pb2.EpicResponse.SerializeToString,
            ),
            'DeleteEpic': grpc.unary_unary_rpc_method_handler(
                    servicer.DeleteEpic,
                    request_deserializer=pm__pb2.DeleteEpicRequest.FromString,
                    response_serializer=pm__pb2.DeleteEpicResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'project.ProjectService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('project.ProjectService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class ProjectService(object):
    """Missing associated documentation comment in .proto file."""

    @staticmethod
    def CreateProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project.ProjectService/CreateProject',
            pm__pb2.CreateProjectRequest.SerializeToString,
            pm__pb2.ProjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project.ProjectService/GetProject',
            pm__pb2.GetProjectRequest.SerializeToString,
            pm__pb2.ProjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project.ProjectService/UpdateProject',
            pm__pb2.UpdateProjectRequest.SerializeToString,
            pm__pb2.ProjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProjectImg(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project.ProjectService/UpdateProjectImg',
            pm__pb2.UpdateProjectImgRequest.SerializeToString,
            pm__pb2.ProjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateProjectUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project.ProjectService/UpdateProjectUsers',
            pm__pb2.UpdateProjectUsersRequest.SerializeToString,
            pm__pb2.UpdateProjectUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteProject(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project.ProjectService/DeleteProject',
            pm__pb2.DeleteProjectRequest.SerializeToString,
            pm__pb2.DeleteProjectResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetUserProjects(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project.ProjectService/GetUserProjects',
            pm__pb2.GetUserProjectsRequest.SerializeToString,
            pm__pb2.UserProjectsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProjectUsers(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project.ProjectService/GetProjectUsers',
            pm__pb2.GetProjectUsersRequest.SerializeToString,
            pm__pb2.ProjectUsersResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetSprint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project.ProjectService/GetSprint',
            pm__pb2.GetSprintRequest.SerializeToString,
            pm__pb2.SprintResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProjectSprints(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project.ProjectService/GetProjectSprints',
            pm__pb2.GetProjectSprintsRequest.SerializeToString,
            pm__pb2.ProjectSprintsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateSprint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project.ProjectService/CreateSprint',
            pm__pb2.CreateSprintRequest.SerializeToString,
            pm__pb2.SprintResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateSprint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project.ProjectService/UpdateSprint',
            pm__pb2.UpdateSprintRequest.SerializeToString,
            pm__pb2.SprintResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteSprint(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project.ProjectService/DeleteSprint',
            pm__pb2.DeleteSprintRequest.SerializeToString,
            pm__pb2.DeleteSprintResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetEpic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project.ProjectService/GetEpic',
            pm__pb2.GetEpicRequest.SerializeToString,
            pm__pb2.EpicResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def GetProjectEpics(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project.ProjectService/GetProjectEpics',
            pm__pb2.GetProjectEpicsRequest.SerializeToString,
            pm__pb2.ProjectEpicsResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def CreateEpic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project.ProjectService/CreateEpic',
            pm__pb2.CreateEpicRequest.SerializeToString,
            pm__pb2.EpicResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def UpdateEpic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project.ProjectService/UpdateEpic',
            pm__pb2.UpdateEpicRequest.SerializeToString,
            pm__pb2.EpicResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def DeleteEpic(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/project.ProjectService/DeleteEpic',
            pm__pb2.DeleteEpicRequest.SerializeToString,
            pm__pb2.DeleteEpicResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
